/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'overview',
        'getting-started',
        'quickstart',
        'workflow',
      ],
    },
    {
      type: 'category',
      label: 'Core Tools',
      items: [
        'entity-details',
        'map',
        'entity-analytics',
        'charts-list',
        'charts-create',
        'charts-detail',
      ],
    },
    {
      type: 'category',
      label: 'How‑to Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'how-to',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'global-search-and-navigation',
        'filters-system',
        'storage-and-persistence',
        'cookies-and-policies',
        'deeplinks-and-python-tools',
        'error-and-telemetry',
      ],
    },
    {
      type: 'category',
      label: 'Advanced (for developers)',
      items: [
        'data-and-analytics-utilities',
        'performance-and-routing',
      ],
    },
    {
      type: 'category',
      label: 'Help',
      items: [
        'faq',
        'glossary',
      ],
    },
  ],
};

module.exports = sidebars;


