/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as MapImport } from './routes/map'
import { Route as EntityAnalyticsImport } from './routes/entity-analytics'
import { Route as CookiesImport } from './routes/cookies'
import { Route as CookiePolicyImport } from './routes/cookie-policy'
import { Route as EntitiesCuiImport } from './routes/entities.$cui'
import { Route as ChartsChartIdRouteImport } from './routes/charts/$chartId/route'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ChartsIndexLazyImport = createFileRoute('/charts/')()
const ChartsNewLazyImport = createFileRoute('/charts/new')()
const ChartsChartIdIndexLazyImport = createFileRoute('/charts/$chartId/')()

// Create/Update Routes

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))

const MapRoute = MapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))

const EntityAnalyticsRoute = EntityAnalyticsImport.update({
  id: '/entity-analytics',
  path: '/entity-analytics',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/entity-analytics.lazy').then((d) => d.Route),
)

const CookiesRoute = CookiesImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cookies.lazy').then((d) => d.Route))

const CookiePolicyRoute = CookiePolicyImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cookie-policy.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ChartsIndexLazyRoute = ChartsIndexLazyImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/charts/index.lazy').then((d) => d.Route))

const ChartsNewLazyRoute = ChartsNewLazyImport.update({
  id: '/charts/new',
  path: '/charts/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/charts/new.lazy').then((d) => d.Route))

const EntitiesCuiRoute = EntitiesCuiImport.update({
  id: '/entities/$cui',
  path: '/entities/$cui',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/entities.$cui.lazy').then((d) => d.Route))

const ChartsChartIdRouteRoute = ChartsChartIdRouteImport.update({
  id: '/charts/$chartId',
  path: '/charts/$chartId',
  getParentRoute: () => rootRoute,
} as any)

const ChartsChartIdIndexLazyRoute = ChartsChartIdIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChartsChartIdRouteRoute,
} as any).lazy(() =>
  import('./routes/charts/$chartId/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyImport
      parentRoute: typeof rootRoute
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesImport
      parentRoute: typeof rootRoute
    }
    '/entity-analytics': {
      id: '/entity-analytics'
      path: '/entity-analytics'
      fullPath: '/entity-analytics'
      preLoaderRoute: typeof EntityAnalyticsImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/charts/$chartId': {
      id: '/charts/$chartId'
      path: '/charts/$chartId'
      fullPath: '/charts/$chartId'
      preLoaderRoute: typeof ChartsChartIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/entities/$cui': {
      id: '/entities/$cui'
      path: '/entities/$cui'
      fullPath: '/entities/$cui'
      preLoaderRoute: typeof EntitiesCuiImport
      parentRoute: typeof rootRoute
    }
    '/charts/new': {
      id: '/charts/new'
      path: '/charts/new'
      fullPath: '/charts/new'
      preLoaderRoute: typeof ChartsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/charts/$chartId/': {
      id: '/charts/$chartId/'
      path: '/'
      fullPath: '/charts/$chartId/'
      preLoaderRoute: typeof ChartsChartIdIndexLazyImport
      parentRoute: typeof ChartsChartIdRouteImport
    }
  }
}

// Create and export the route tree

interface ChartsChartIdRouteRouteChildren {
  ChartsChartIdIndexLazyRoute: typeof ChartsChartIdIndexLazyRoute
}

const ChartsChartIdRouteRouteChildren: ChartsChartIdRouteRouteChildren = {
  ChartsChartIdIndexLazyRoute: ChartsChartIdIndexLazyRoute,
}

const ChartsChartIdRouteRouteWithChildren =
  ChartsChartIdRouteRoute._addFileChildren(ChartsChartIdRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/charts/$chartId': typeof ChartsChartIdRouteRouteWithChildren
  '/entities/$cui': typeof EntitiesCuiRoute
  '/charts/new': typeof ChartsNewLazyRoute
  '/charts': typeof ChartsIndexLazyRoute
  '/charts/$chartId/': typeof ChartsChartIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/entities/$cui': typeof EntitiesCuiRoute
  '/charts/new': typeof ChartsNewLazyRoute
  '/charts': typeof ChartsIndexLazyRoute
  '/charts/$chartId': typeof ChartsChartIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/charts/$chartId': typeof ChartsChartIdRouteRouteWithChildren
  '/entities/$cui': typeof EntitiesCuiRoute
  '/charts/new': typeof ChartsNewLazyRoute
  '/charts/': typeof ChartsIndexLazyRoute
  '/charts/$chartId/': typeof ChartsChartIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/charts/$chartId'
    | '/entities/$cui'
    | '/charts/new'
    | '/charts'
    | '/charts/$chartId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/entities/$cui'
    | '/charts/new'
    | '/charts'
    | '/charts/$chartId'
  id:
    | '__root__'
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/charts/$chartId'
    | '/entities/$cui'
    | '/charts/new'
    | '/charts/'
    | '/charts/$chartId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CookiesRoute: typeof CookiesRoute
  EntityAnalyticsRoute: typeof EntityAnalyticsRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  ChartsChartIdRouteRoute: typeof ChartsChartIdRouteRouteWithChildren
  EntitiesCuiRoute: typeof EntitiesCuiRoute
  ChartsNewLazyRoute: typeof ChartsNewLazyRoute
  ChartsIndexLazyRoute: typeof ChartsIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CookiesRoute: CookiesRoute,
  EntityAnalyticsRoute: EntityAnalyticsRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  ChartsChartIdRouteRoute: ChartsChartIdRouteRouteWithChildren,
  EntitiesCuiRoute: EntitiesCuiRoute,
  ChartsNewLazyRoute: ChartsNewLazyRoute,
  ChartsIndexLazyRoute: ChartsIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cookie-policy",
        "/cookies",
        "/entity-analytics",
        "/map",
        "/privacy",
        "/charts/$chartId",
        "/entities/$cui",
        "/charts/new",
        "/charts/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cookie-policy": {
      "filePath": "cookie-policy.tsx"
    },
    "/cookies": {
      "filePath": "cookies.tsx"
    },
    "/entity-analytics": {
      "filePath": "entity-analytics.tsx"
    },
    "/map": {
      "filePath": "map.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/charts/$chartId": {
      "filePath": "charts/$chartId/route.tsx",
      "children": [
        "/charts/$chartId/"
      ]
    },
    "/entities/$cui": {
      "filePath": "entities.$cui.tsx"
    },
    "/charts/new": {
      "filePath": "charts/new.lazy.tsx"
    },
    "/charts/": {
      "filePath": "charts/index.lazy.tsx"
    },
    "/charts/$chartId/": {
      "filePath": "charts/$chartId/index.lazy.tsx",
      "parent": "/charts/$chartId"
    }
  }
}
ROUTE_MANIFEST_END */
