/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MapRouteImport } from './routes/map'
import { Route as EntityAnalyticsRouteImport } from './routes/entity-analytics'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as ShareCodeRouteImport } from './routes/share.$code'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as EntitiesCuiRouteImport } from './routes/entities.$cui'
import { Route as AlertsNewRouteImport } from './routes/alerts/new'
import { Route as RoLearningRouteRouteImport } from './routes/ro/learning/route'
import { Route as EnLearningRouteRouteImport } from './routes/en/learning/route'
import { Route as ChartsChartIdRouteRouteImport } from './routes/charts/$chartId/route'
import { Route as AlertsAlertIdRouteRouteImport } from './routes/alerts/$alertId/route'
import { Route as RoLearningIndexRouteImport } from './routes/ro/learning/index'
import { Route as EnLearningIndexRouteImport } from './routes/en/learning/index'
import { Route as ClassificationsFunctionalIndexRouteImport } from './routes/classifications/functional/index'
import { Route as ClassificationsEconomicIndexRouteImport } from './routes/classifications/economic/index'
import { Route as ClassificationsFunctionalCodeRouteImport } from './routes/classifications/functional/$code'
import { Route as ClassificationsEconomicCodeRouteImport } from './routes/classifications/economic/$code'
import { Route as RoLearningOrganizationHierarchyRouteImport } from './routes/ro/learning/organization/hierarchy'
import { Route as RoLearningOrganizationFlowRouteImport } from './routes/ro/learning/organization/flow'
import { Route as RoLearningFundamentalsStructureRouteImport } from './routes/ro/learning/fundamentals/structure'
import { Route as RoLearningFundamentalsBasicsRouteImport } from './routes/ro/learning/fundamentals/basics'
import { Route as RoLearningAdvancedConceptsRouteImport } from './routes/ro/learning/advanced/concepts'
import { Route as EnLearningOrganizationHierarchyRouteImport } from './routes/en/learning/organization/hierarchy'
import { Route as EnLearningOrganizationFlowRouteImport } from './routes/en/learning/organization/flow'
import { Route as EnLearningFundamentalsStructureRouteImport } from './routes/en/learning/fundamentals/structure'
import { Route as EnLearningFundamentalsBasicsRouteImport } from './routes/en/learning/fundamentals/basics'
import { Route as EnLearningAdvancedConceptsRouteImport } from './routes/en/learning/advanced/concepts'

const TermsLazyRouteImport = createFileRoute('/terms')()
const BudgetExplorerLazyRouteImport = createFileRoute('/budget-explorer')()
const IndexLazyRouteImport = createFileRoute('/')()
const ChartsIndexLazyRouteImport = createFileRoute('/charts/')()
const ResearchEmployeesDataLazyRouteImport = createFileRoute(
  '/research/employees-data',
)()
const ChartsNewLazyRouteImport = createFileRoute('/charts/new')()
const ChartsChartIdIndexLazyRouteImport = createFileRoute('/charts/$chartId/')()
const AlertsAlertIdIndexLazyRouteImport = createFileRoute('/alerts/$alertId/')()

const TermsLazyRoute = TermsLazyRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const BudgetExplorerLazyRoute = BudgetExplorerLazyRouteImport.update({
  id: '/budget-explorer',
  path: '/budget-explorer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/budget-explorer.lazy').then((d) => d.Route),
)
const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))
const EntityAnalyticsRoute = EntityAnalyticsRouteImport.update({
  id: '/entity-analytics',
  path: '/entity-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/entity-analytics.lazy').then((d) => d.Route),
)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookies.lazy').then((d) => d.Route))
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookie-policy.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ChartsIndexLazyRoute = ChartsIndexLazyRouteImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/charts/index.lazy').then((d) => d.Route))
const ResearchEmployeesDataLazyRoute =
  ResearchEmployeesDataLazyRouteImport.update({
    id: '/research/employees-data',
    path: '/research/employees-data',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/research/employees-data.lazy').then((d) => d.Route),
  )
const ChartsNewLazyRoute = ChartsNewLazyRouteImport.update({
  id: '/charts/new',
  path: '/charts/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/charts/new.lazy').then((d) => d.Route))
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareCodeRoute = ShareCodeRouteImport.update({
  id: '/share/$code',
  path: '/share/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesCuiRoute = EntitiesCuiRouteImport.update({
  id: '/entities/$cui',
  path: '/entities/$cui',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/entities.$cui.lazy').then((d) => d.Route))
const AlertsNewRoute = AlertsNewRouteImport.update({
  id: '/alerts/new',
  path: '/alerts/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/alerts/new.lazy').then((d) => d.Route))
const RoLearningRouteRoute = RoLearningRouteRouteImport.update({
  id: '/ro/learning',
  path: '/ro/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLearningRouteRoute = EnLearningRouteRouteImport.update({
  id: '/en/learning',
  path: '/en/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsChartIdRouteRoute = ChartsChartIdRouteRouteImport.update({
  id: '/charts/$chartId',
  path: '/charts/$chartId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRouteRoute = AlertsAlertIdRouteRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsChartIdIndexLazyRoute = ChartsChartIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChartsChartIdRouteRoute,
} as any).lazy(() =>
  import('./routes/charts/$chartId/index.lazy').then((d) => d.Route),
)
const AlertsAlertIdIndexLazyRoute = AlertsAlertIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlertsAlertIdRouteRoute,
} as any).lazy(() =>
  import('./routes/alerts/$alertId/index.lazy').then((d) => d.Route),
)
const RoLearningIndexRoute = RoLearningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoLearningRouteRoute,
} as any)
const EnLearningIndexRoute = EnLearningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnLearningRouteRoute,
} as any)
const ClassificationsFunctionalIndexRoute =
  ClassificationsFunctionalIndexRouteImport.update({
    id: '/classifications/functional/',
    path: '/classifications/functional/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/functional/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ClassificationsEconomicIndexRoute =
  ClassificationsEconomicIndexRouteImport.update({
    id: '/classifications/economic/',
    path: '/classifications/economic/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/economic/index.lazy').then((d) => d.Route),
  )
const ClassificationsFunctionalCodeRoute =
  ClassificationsFunctionalCodeRouteImport.update({
    id: '/classifications/functional/$code',
    path: '/classifications/functional/$code',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/functional/$code.lazy').then(
      (d) => d.Route,
    ),
  )
const ClassificationsEconomicCodeRoute =
  ClassificationsEconomicCodeRouteImport.update({
    id: '/classifications/economic/$code',
    path: '/classifications/economic/$code',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/economic/$code.lazy').then((d) => d.Route),
  )
const RoLearningOrganizationHierarchyRoute =
  RoLearningOrganizationHierarchyRouteImport.update({
    id: '/organization/hierarchy',
    path: '/organization/hierarchy',
    getParentRoute: () => RoLearningRouteRoute,
  } as any)
const RoLearningOrganizationFlowRoute =
  RoLearningOrganizationFlowRouteImport.update({
    id: '/organization/flow',
    path: '/organization/flow',
    getParentRoute: () => RoLearningRouteRoute,
  } as any)
const RoLearningFundamentalsStructureRoute =
  RoLearningFundamentalsStructureRouteImport.update({
    id: '/fundamentals/structure',
    path: '/fundamentals/structure',
    getParentRoute: () => RoLearningRouteRoute,
  } as any)
const RoLearningFundamentalsBasicsRoute =
  RoLearningFundamentalsBasicsRouteImport.update({
    id: '/fundamentals/basics',
    path: '/fundamentals/basics',
    getParentRoute: () => RoLearningRouteRoute,
  } as any)
const RoLearningAdvancedConceptsRoute =
  RoLearningAdvancedConceptsRouteImport.update({
    id: '/advanced/concepts',
    path: '/advanced/concepts',
    getParentRoute: () => RoLearningRouteRoute,
  } as any)
const EnLearningOrganizationHierarchyRoute =
  EnLearningOrganizationHierarchyRouteImport.update({
    id: '/organization/hierarchy',
    path: '/organization/hierarchy',
    getParentRoute: () => EnLearningRouteRoute,
  } as any)
const EnLearningOrganizationFlowRoute =
  EnLearningOrganizationFlowRouteImport.update({
    id: '/organization/flow',
    path: '/organization/flow',
    getParentRoute: () => EnLearningRouteRoute,
  } as any)
const EnLearningFundamentalsStructureRoute =
  EnLearningFundamentalsStructureRouteImport.update({
    id: '/fundamentals/structure',
    path: '/fundamentals/structure',
    getParentRoute: () => EnLearningRouteRoute,
  } as any)
const EnLearningFundamentalsBasicsRoute =
  EnLearningFundamentalsBasicsRouteImport.update({
    id: '/fundamentals/basics',
    path: '/fundamentals/basics',
    getParentRoute: () => EnLearningRouteRoute,
  } as any)
const EnLearningAdvancedConceptsRoute =
  EnLearningAdvancedConceptsRouteImport.update({
    id: '/advanced/concepts',
    path: '/advanced/concepts',
    getParentRoute: () => EnLearningRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/budget-explorer': typeof BudgetExplorerLazyRoute
  '/terms': typeof TermsLazyRoute
  '/alerts/$alertId': typeof AlertsAlertIdRouteRouteWithChildren
  '/charts/$chartId': typeof ChartsChartIdRouteRouteWithChildren
  '/en/learning': typeof EnLearningRouteRouteWithChildren
  '/ro/learning': typeof RoLearningRouteRouteWithChildren
  '/alerts/new': typeof AlertsNewRoute
  '/entities/$cui': typeof EntitiesCuiRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/charts/new': typeof ChartsNewLazyRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/charts': typeof ChartsIndexLazyRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/classifications/economic': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional': typeof ClassificationsFunctionalIndexRoute
  '/en/learning/': typeof EnLearningIndexRoute
  '/ro/learning/': typeof RoLearningIndexRoute
  '/alerts/$alertId/': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId/': typeof ChartsChartIdIndexLazyRoute
  '/en/learning/advanced/concepts': typeof EnLearningAdvancedConceptsRoute
  '/en/learning/fundamentals/basics': typeof EnLearningFundamentalsBasicsRoute
  '/en/learning/fundamentals/structure': typeof EnLearningFundamentalsStructureRoute
  '/en/learning/organization/flow': typeof EnLearningOrganizationFlowRoute
  '/en/learning/organization/hierarchy': typeof EnLearningOrganizationHierarchyRoute
  '/ro/learning/advanced/concepts': typeof RoLearningAdvancedConceptsRoute
  '/ro/learning/fundamentals/basics': typeof RoLearningFundamentalsBasicsRoute
  '/ro/learning/fundamentals/structure': typeof RoLearningFundamentalsStructureRoute
  '/ro/learning/organization/flow': typeof RoLearningOrganizationFlowRoute
  '/ro/learning/organization/hierarchy': typeof RoLearningOrganizationHierarchyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/budget-explorer': typeof BudgetExplorerLazyRoute
  '/terms': typeof TermsLazyRoute
  '/alerts/new': typeof AlertsNewRoute
  '/entities/$cui': typeof EntitiesCuiRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/charts/new': typeof ChartsNewLazyRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/charts': typeof ChartsIndexLazyRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/classifications/economic': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional': typeof ClassificationsFunctionalIndexRoute
  '/en/learning': typeof EnLearningIndexRoute
  '/ro/learning': typeof RoLearningIndexRoute
  '/alerts/$alertId': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId': typeof ChartsChartIdIndexLazyRoute
  '/en/learning/advanced/concepts': typeof EnLearningAdvancedConceptsRoute
  '/en/learning/fundamentals/basics': typeof EnLearningFundamentalsBasicsRoute
  '/en/learning/fundamentals/structure': typeof EnLearningFundamentalsStructureRoute
  '/en/learning/organization/flow': typeof EnLearningOrganizationFlowRoute
  '/en/learning/organization/hierarchy': typeof EnLearningOrganizationHierarchyRoute
  '/ro/learning/advanced/concepts': typeof RoLearningAdvancedConceptsRoute
  '/ro/learning/fundamentals/basics': typeof RoLearningFundamentalsBasicsRoute
  '/ro/learning/fundamentals/structure': typeof RoLearningFundamentalsStructureRoute
  '/ro/learning/organization/flow': typeof RoLearningOrganizationFlowRoute
  '/ro/learning/organization/hierarchy': typeof RoLearningOrganizationHierarchyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/budget-explorer': typeof BudgetExplorerLazyRoute
  '/terms': typeof TermsLazyRoute
  '/alerts/$alertId': typeof AlertsAlertIdRouteRouteWithChildren
  '/charts/$chartId': typeof ChartsChartIdRouteRouteWithChildren
  '/en/learning': typeof EnLearningRouteRouteWithChildren
  '/ro/learning': typeof RoLearningRouteRouteWithChildren
  '/alerts/new': typeof AlertsNewRoute
  '/entities/$cui': typeof EntitiesCuiRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/charts/new': typeof ChartsNewLazyRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/charts/': typeof ChartsIndexLazyRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/classifications/economic/': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional/': typeof ClassificationsFunctionalIndexRoute
  '/en/learning/': typeof EnLearningIndexRoute
  '/ro/learning/': typeof RoLearningIndexRoute
  '/alerts/$alertId/': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId/': typeof ChartsChartIdIndexLazyRoute
  '/en/learning/advanced/concepts': typeof EnLearningAdvancedConceptsRoute
  '/en/learning/fundamentals/basics': typeof EnLearningFundamentalsBasicsRoute
  '/en/learning/fundamentals/structure': typeof EnLearningFundamentalsStructureRoute
  '/en/learning/organization/flow': typeof EnLearningOrganizationFlowRoute
  '/en/learning/organization/hierarchy': typeof EnLearningOrganizationHierarchyRoute
  '/ro/learning/advanced/concepts': typeof RoLearningAdvancedConceptsRoute
  '/ro/learning/fundamentals/basics': typeof RoLearningFundamentalsBasicsRoute
  '/ro/learning/fundamentals/structure': typeof RoLearningFundamentalsStructureRoute
  '/ro/learning/organization/flow': typeof RoLearningOrganizationFlowRoute
  '/ro/learning/organization/hierarchy': typeof RoLearningOrganizationHierarchyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/budget-explorer'
    | '/terms'
    | '/alerts/$alertId'
    | '/charts/$chartId'
    | '/en/learning'
    | '/ro/learning'
    | '/alerts/new'
    | '/entities/$cui'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/charts/new'
    | '/research/employees-data'
    | '/charts'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/classifications/economic'
    | '/classifications/functional'
    | '/en/learning/'
    | '/ro/learning/'
    | '/alerts/$alertId/'
    | '/charts/$chartId/'
    | '/en/learning/advanced/concepts'
    | '/en/learning/fundamentals/basics'
    | '/en/learning/fundamentals/structure'
    | '/en/learning/organization/flow'
    | '/en/learning/organization/hierarchy'
    | '/ro/learning/advanced/concepts'
    | '/ro/learning/fundamentals/basics'
    | '/ro/learning/fundamentals/structure'
    | '/ro/learning/organization/flow'
    | '/ro/learning/organization/hierarchy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/budget-explorer'
    | '/terms'
    | '/alerts/new'
    | '/entities/$cui'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/charts/new'
    | '/research/employees-data'
    | '/charts'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/classifications/economic'
    | '/classifications/functional'
    | '/en/learning'
    | '/ro/learning'
    | '/alerts/$alertId'
    | '/charts/$chartId'
    | '/en/learning/advanced/concepts'
    | '/en/learning/fundamentals/basics'
    | '/en/learning/fundamentals/structure'
    | '/en/learning/organization/flow'
    | '/en/learning/organization/hierarchy'
    | '/ro/learning/advanced/concepts'
    | '/ro/learning/fundamentals/basics'
    | '/ro/learning/fundamentals/structure'
    | '/ro/learning/organization/flow'
    | '/ro/learning/organization/hierarchy'
  id:
    | '__root__'
    | '/'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/budget-explorer'
    | '/terms'
    | '/alerts/$alertId'
    | '/charts/$chartId'
    | '/en/learning'
    | '/ro/learning'
    | '/alerts/new'
    | '/entities/$cui'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/charts/new'
    | '/research/employees-data'
    | '/charts/'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/classifications/economic/'
    | '/classifications/functional/'
    | '/en/learning/'
    | '/ro/learning/'
    | '/alerts/$alertId/'
    | '/charts/$chartId/'
    | '/en/learning/advanced/concepts'
    | '/en/learning/fundamentals/basics'
    | '/en/learning/fundamentals/structure'
    | '/en/learning/organization/flow'
    | '/en/learning/organization/hierarchy'
    | '/ro/learning/advanced/concepts'
    | '/ro/learning/fundamentals/basics'
    | '/ro/learning/fundamentals/structure'
    | '/ro/learning/organization/flow'
    | '/ro/learning/organization/hierarchy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CookiesRoute: typeof CookiesRoute
  EntityAnalyticsRoute: typeof EntityAnalyticsRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  TestErrorRoute: typeof TestErrorRoute
  BudgetExplorerLazyRoute: typeof BudgetExplorerLazyRoute
  TermsLazyRoute: typeof TermsLazyRoute
  AlertsAlertIdRouteRoute: typeof AlertsAlertIdRouteRouteWithChildren
  ChartsChartIdRouteRoute: typeof ChartsChartIdRouteRouteWithChildren
  EnLearningRouteRoute: typeof EnLearningRouteRouteWithChildren
  RoLearningRouteRoute: typeof RoLearningRouteRouteWithChildren
  AlertsNewRoute: typeof AlertsNewRoute
  EntitiesCuiRoute: typeof EntitiesCuiRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  ShareCodeRoute: typeof ShareCodeRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  ChartsNewLazyRoute: typeof ChartsNewLazyRoute
  ResearchEmployeesDataLazyRoute: typeof ResearchEmployeesDataLazyRoute
  ChartsIndexLazyRoute: typeof ChartsIndexLazyRoute
  ClassificationsEconomicCodeRoute: typeof ClassificationsEconomicCodeRoute
  ClassificationsFunctionalCodeRoute: typeof ClassificationsFunctionalCodeRoute
  ClassificationsEconomicIndexRoute: typeof ClassificationsEconomicIndexRoute
  ClassificationsFunctionalIndexRoute: typeof ClassificationsFunctionalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-explorer': {
      id: '/budget-explorer'
      path: '/budget-explorer'
      fullPath: '/budget-explorer'
      preLoaderRoute: typeof BudgetExplorerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity-analytics': {
      id: '/entity-analytics'
      path: '/entity-analytics'
      fullPath: '/entity-analytics'
      preLoaderRoute: typeof EntityAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/employees-data': {
      id: '/research/employees-data'
      path: '/research/employees-data'
      fullPath: '/research/employees-data'
      preLoaderRoute: typeof ResearchEmployeesDataLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/new': {
      id: '/charts/new'
      path: '/charts/new'
      fullPath: '/charts/new'
      preLoaderRoute: typeof ChartsNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$code': {
      id: '/share/$code'
      path: '/share/$code'
      fullPath: '/share/$code'
      preLoaderRoute: typeof ShareCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$cui': {
      id: '/entities/$cui'
      path: '/entities/$cui'
      fullPath: '/entities/$cui'
      preLoaderRoute: typeof EntitiesCuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/new': {
      id: '/alerts/new'
      path: '/alerts/new'
      fullPath: '/alerts/new'
      preLoaderRoute: typeof AlertsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ro/learning': {
      id: '/ro/learning'
      path: '/ro/learning'
      fullPath: '/ro/learning'
      preLoaderRoute: typeof RoLearningRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/learning': {
      id: '/en/learning'
      path: '/en/learning'
      fullPath: '/en/learning'
      preLoaderRoute: typeof EnLearningRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$chartId': {
      id: '/charts/$chartId'
      path: '/charts/$chartId'
      fullPath: '/charts/$chartId'
      preLoaderRoute: typeof ChartsChartIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$chartId/': {
      id: '/charts/$chartId/'
      path: '/'
      fullPath: '/charts/$chartId/'
      preLoaderRoute: typeof ChartsChartIdIndexLazyRouteImport
      parentRoute: typeof ChartsChartIdRouteRoute
    }
    '/alerts/$alertId/': {
      id: '/alerts/$alertId/'
      path: '/'
      fullPath: '/alerts/$alertId/'
      preLoaderRoute: typeof AlertsAlertIdIndexLazyRouteImport
      parentRoute: typeof AlertsAlertIdRouteRoute
    }
    '/ro/learning/': {
      id: '/ro/learning/'
      path: '/'
      fullPath: '/ro/learning/'
      preLoaderRoute: typeof RoLearningIndexRouteImport
      parentRoute: typeof RoLearningRouteRoute
    }
    '/en/learning/': {
      id: '/en/learning/'
      path: '/'
      fullPath: '/en/learning/'
      preLoaderRoute: typeof EnLearningIndexRouteImport
      parentRoute: typeof EnLearningRouteRoute
    }
    '/classifications/functional/': {
      id: '/classifications/functional/'
      path: '/classifications/functional'
      fullPath: '/classifications/functional'
      preLoaderRoute: typeof ClassificationsFunctionalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications/economic/': {
      id: '/classifications/economic/'
      path: '/classifications/economic'
      fullPath: '/classifications/economic'
      preLoaderRoute: typeof ClassificationsEconomicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications/functional/$code': {
      id: '/classifications/functional/$code'
      path: '/classifications/functional/$code'
      fullPath: '/classifications/functional/$code'
      preLoaderRoute: typeof ClassificationsFunctionalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications/economic/$code': {
      id: '/classifications/economic/$code'
      path: '/classifications/economic/$code'
      fullPath: '/classifications/economic/$code'
      preLoaderRoute: typeof ClassificationsEconomicCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ro/learning/organization/hierarchy': {
      id: '/ro/learning/organization/hierarchy'
      path: '/organization/hierarchy'
      fullPath: '/ro/learning/organization/hierarchy'
      preLoaderRoute: typeof RoLearningOrganizationHierarchyRouteImport
      parentRoute: typeof RoLearningRouteRoute
    }
    '/ro/learning/organization/flow': {
      id: '/ro/learning/organization/flow'
      path: '/organization/flow'
      fullPath: '/ro/learning/organization/flow'
      preLoaderRoute: typeof RoLearningOrganizationFlowRouteImport
      parentRoute: typeof RoLearningRouteRoute
    }
    '/ro/learning/fundamentals/structure': {
      id: '/ro/learning/fundamentals/structure'
      path: '/fundamentals/structure'
      fullPath: '/ro/learning/fundamentals/structure'
      preLoaderRoute: typeof RoLearningFundamentalsStructureRouteImport
      parentRoute: typeof RoLearningRouteRoute
    }
    '/ro/learning/fundamentals/basics': {
      id: '/ro/learning/fundamentals/basics'
      path: '/fundamentals/basics'
      fullPath: '/ro/learning/fundamentals/basics'
      preLoaderRoute: typeof RoLearningFundamentalsBasicsRouteImport
      parentRoute: typeof RoLearningRouteRoute
    }
    '/ro/learning/advanced/concepts': {
      id: '/ro/learning/advanced/concepts'
      path: '/advanced/concepts'
      fullPath: '/ro/learning/advanced/concepts'
      preLoaderRoute: typeof RoLearningAdvancedConceptsRouteImport
      parentRoute: typeof RoLearningRouteRoute
    }
    '/en/learning/organization/hierarchy': {
      id: '/en/learning/organization/hierarchy'
      path: '/organization/hierarchy'
      fullPath: '/en/learning/organization/hierarchy'
      preLoaderRoute: typeof EnLearningOrganizationHierarchyRouteImport
      parentRoute: typeof EnLearningRouteRoute
    }
    '/en/learning/organization/flow': {
      id: '/en/learning/organization/flow'
      path: '/organization/flow'
      fullPath: '/en/learning/organization/flow'
      preLoaderRoute: typeof EnLearningOrganizationFlowRouteImport
      parentRoute: typeof EnLearningRouteRoute
    }
    '/en/learning/fundamentals/structure': {
      id: '/en/learning/fundamentals/structure'
      path: '/fundamentals/structure'
      fullPath: '/en/learning/fundamentals/structure'
      preLoaderRoute: typeof EnLearningFundamentalsStructureRouteImport
      parentRoute: typeof EnLearningRouteRoute
    }
    '/en/learning/fundamentals/basics': {
      id: '/en/learning/fundamentals/basics'
      path: '/fundamentals/basics'
      fullPath: '/en/learning/fundamentals/basics'
      preLoaderRoute: typeof EnLearningFundamentalsBasicsRouteImport
      parentRoute: typeof EnLearningRouteRoute
    }
    '/en/learning/advanced/concepts': {
      id: '/en/learning/advanced/concepts'
      path: '/advanced/concepts'
      fullPath: '/en/learning/advanced/concepts'
      preLoaderRoute: typeof EnLearningAdvancedConceptsRouteImport
      parentRoute: typeof EnLearningRouteRoute
    }
  }
}

interface AlertsAlertIdRouteRouteChildren {
  AlertsAlertIdIndexLazyRoute: typeof AlertsAlertIdIndexLazyRoute
}

const AlertsAlertIdRouteRouteChildren: AlertsAlertIdRouteRouteChildren = {
  AlertsAlertIdIndexLazyRoute: AlertsAlertIdIndexLazyRoute,
}

const AlertsAlertIdRouteRouteWithChildren =
  AlertsAlertIdRouteRoute._addFileChildren(AlertsAlertIdRouteRouteChildren)

interface ChartsChartIdRouteRouteChildren {
  ChartsChartIdIndexLazyRoute: typeof ChartsChartIdIndexLazyRoute
}

const ChartsChartIdRouteRouteChildren: ChartsChartIdRouteRouteChildren = {
  ChartsChartIdIndexLazyRoute: ChartsChartIdIndexLazyRoute,
}

const ChartsChartIdRouteRouteWithChildren =
  ChartsChartIdRouteRoute._addFileChildren(ChartsChartIdRouteRouteChildren)

interface EnLearningRouteRouteChildren {
  EnLearningIndexRoute: typeof EnLearningIndexRoute
  EnLearningAdvancedConceptsRoute: typeof EnLearningAdvancedConceptsRoute
  EnLearningFundamentalsBasicsRoute: typeof EnLearningFundamentalsBasicsRoute
  EnLearningFundamentalsStructureRoute: typeof EnLearningFundamentalsStructureRoute
  EnLearningOrganizationFlowRoute: typeof EnLearningOrganizationFlowRoute
  EnLearningOrganizationHierarchyRoute: typeof EnLearningOrganizationHierarchyRoute
}

const EnLearningRouteRouteChildren: EnLearningRouteRouteChildren = {
  EnLearningIndexRoute: EnLearningIndexRoute,
  EnLearningAdvancedConceptsRoute: EnLearningAdvancedConceptsRoute,
  EnLearningFundamentalsBasicsRoute: EnLearningFundamentalsBasicsRoute,
  EnLearningFundamentalsStructureRoute: EnLearningFundamentalsStructureRoute,
  EnLearningOrganizationFlowRoute: EnLearningOrganizationFlowRoute,
  EnLearningOrganizationHierarchyRoute: EnLearningOrganizationHierarchyRoute,
}

const EnLearningRouteRouteWithChildren = EnLearningRouteRoute._addFileChildren(
  EnLearningRouteRouteChildren,
)

interface RoLearningRouteRouteChildren {
  RoLearningIndexRoute: typeof RoLearningIndexRoute
  RoLearningAdvancedConceptsRoute: typeof RoLearningAdvancedConceptsRoute
  RoLearningFundamentalsBasicsRoute: typeof RoLearningFundamentalsBasicsRoute
  RoLearningFundamentalsStructureRoute: typeof RoLearningFundamentalsStructureRoute
  RoLearningOrganizationFlowRoute: typeof RoLearningOrganizationFlowRoute
  RoLearningOrganizationHierarchyRoute: typeof RoLearningOrganizationHierarchyRoute
}

const RoLearningRouteRouteChildren: RoLearningRouteRouteChildren = {
  RoLearningIndexRoute: RoLearningIndexRoute,
  RoLearningAdvancedConceptsRoute: RoLearningAdvancedConceptsRoute,
  RoLearningFundamentalsBasicsRoute: RoLearningFundamentalsBasicsRoute,
  RoLearningFundamentalsStructureRoute: RoLearningFundamentalsStructureRoute,
  RoLearningOrganizationFlowRoute: RoLearningOrganizationFlowRoute,
  RoLearningOrganizationHierarchyRoute: RoLearningOrganizationHierarchyRoute,
}

const RoLearningRouteRouteWithChildren = RoLearningRouteRoute._addFileChildren(
  RoLearningRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CookiesRoute: CookiesRoute,
  EntityAnalyticsRoute: EntityAnalyticsRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  TestErrorRoute: TestErrorRoute,
  BudgetExplorerLazyRoute: BudgetExplorerLazyRoute,
  TermsLazyRoute: TermsLazyRoute,
  AlertsAlertIdRouteRoute: AlertsAlertIdRouteRouteWithChildren,
  ChartsChartIdRouteRoute: ChartsChartIdRouteRouteWithChildren,
  EnLearningRouteRoute: EnLearningRouteRouteWithChildren,
  RoLearningRouteRoute: RoLearningRouteRouteWithChildren,
  AlertsNewRoute: AlertsNewRoute,
  EntitiesCuiRoute: EntitiesCuiRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  ShareCodeRoute: ShareCodeRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  ChartsNewLazyRoute: ChartsNewLazyRoute,
  ResearchEmployeesDataLazyRoute: ResearchEmployeesDataLazyRoute,
  ChartsIndexLazyRoute: ChartsIndexLazyRoute,
  ClassificationsEconomicCodeRoute: ClassificationsEconomicCodeRoute,
  ClassificationsFunctionalCodeRoute: ClassificationsFunctionalCodeRoute,
  ClassificationsEconomicIndexRoute: ClassificationsEconomicIndexRoute,
  ClassificationsFunctionalIndexRoute: ClassificationsFunctionalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
